name: semgrep -> SARIF upload

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip3 install semgrep
      - name: Run semgrep and generate SARIF
        run: |
          semgrep --config semgrep/perf-antipatterns-arkts.yml --exclude node_modules --sarif semgrep.sarif.json
      - name: Upload SARIF to GitHub Code Scanning
        uses: github/code-scanning-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif.json